"""Seeded ground truth for static density reconstruction.

Everything here is host-side NumPy and deterministic in its seed. The truth is
an ``N``-particle **equal-mass** realisation of a Milky-Way-like composite --
bulge, exponential disc, NFW-like halo -- optionally with an LMC-like offset
overdensity realised as more of the *same* equal-mass particles. Equal masses
are what make a pure-position parameterisation sufficient: number density
traces mass density directly, so all structure is encoded in where the
particles are.

The observations the reconstruction fits are accelerations at ``M`` tracer
positions. They are generated by **jaccpot itself** at tight accuracy (high
expansion order, small ``theta``), not by an analytic potential: this section
tests the optimiser and the autodiff path, not FMM accuracy, which section 3
already establishes. The generating configuration is recorded on the truth
object so every results JSON can carry it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Literal, Optional, Tuple

import numpy as np

__all__ = [
    "GroundTruth",
    "TruthConfig",
    "make_ground_truth",
    "sample_composite",
    "sample_tracers",
]

PerturberMode = Literal["none", "lmc_like"]
TracerMode = Literal["independent", "from_particles"]


@dataclass(frozen=True)
class TruthConfig:
    """Generating configuration for one ground-truth realisation.

    Attributes
    ----------
    num_particles : int
        Source particle count ``N``. Every particle carries mass
        ``total_mass / num_particles``.
    num_tracers : int
        Tracer count ``M`` at which accelerations are observed.
    seed : int
        Seed for every random draw in the realisation.
    total_mass : float
        Total source mass, split equally.
    bulge_fraction : float
        Fraction of particles in the bulge component.
    disc_fraction : float
        Fraction of particles in the exponential disc.
    bulge_scale : float
        Bulge scale radius (Hernquist-like density).
    disc_scale_length : float
        Disc radial scale length.
    disc_scale_height : float
        Disc vertical scale height.
    halo_scale : float
        Halo scale radius (NFW-like density, truncated).
    halo_truncation : float
        Halo truncation radius in units of ``halo_scale``.
    perturber : PerturberMode
        ``"none"`` or ``"lmc_like"`` -- an offset Plummer-like overdensity
        realised from the same equal-mass particle pool.
    perturber_fraction : float
        Fraction of particles assigned to the perturber when present.
    perturber_offset : Tuple[float, float, float]
        Perturber centre.
    perturber_scale : float
        Perturber scale radius.
    tracer_mode : TracerMode
        ``"independent"`` samples tracers uniformly in a sphere;
        ``"from_particles"`` places them near source particles. The two give
        different degeneracy structure, which is why both exist.
    tracer_radius : float
        Sphere radius for independent tracers.
    noise_fraction : float
        Fractional Gaussian noise on observed accelerations; ``0.0`` for a
        noiseless run.
    softening : float
        Plummer softening length, fixed and recorded (hard decision 6).
    generating_order : int
        Expansion order used to generate the observations.
    generating_theta : float
        Multipole acceptance parameter used to generate the observations.
    generating_leaf_size : int
        Leaf size used to generate the observations.
    """

    num_particles: int = 1024
    num_tracers: int = 256
    seed: int = 0
    total_mass: float = 1.0
    bulge_fraction: float = 0.15
    disc_fraction: float = 0.45
    bulge_scale: float = 0.15
    disc_scale_length: float = 0.6
    disc_scale_height: float = 0.06
    halo_scale: float = 1.2
    halo_truncation: float = 4.0
    perturber: PerturberMode = "none"
    perturber_fraction: float = 0.05
    perturber_offset: Tuple[float, float, float] = (1.5, -0.8, -0.6)
    perturber_scale: float = 0.2
    tracer_mode: TracerMode = "independent"
    tracer_radius: float = 3.0
    noise_fraction: float = 0.0
    softening: float = 1.0e-2
    generating_order: int = 8
    generating_theta: float = 0.3
    generating_leaf_size: int = 16

    def as_record(self: "TruthConfig") -> Dict[str, Any]:
        """Return a JSON-safe copy for a results file.

        Returns
        -------
        Dict[str, Any]
            Every field, with the tuple offset as a list.
        """
        record = asdict(self)
        record["perturber_offset"] = list(self.perturber_offset)
        return record


def _hernquist_radii(rng: np.random.Generator, n: int, scale: float) -> np.ndarray:
    """Sample Hernquist radii by inverse transform.

    Parameters
    ----------
    rng : np.random.Generator
        Source of randomness.
    n : int
        Sample count.
    scale : float
        Scale radius ``a``.

    Returns
    -------
    np.ndarray
        ``(n,)`` radii. The Hernquist enclosed-mass fraction is
        ``r^2 / (r + a)^2``, inverted as ``r = a sqrt(u) / (1 - sqrt(u))``.
    """
    u = rng.uniform(0.0, 0.98, size=n)
    root = np.sqrt(u)
    return scale * root / (1.0 - root)


def _nfw_radii(
    rng: np.random.Generator, n: int, scale: float, truncation: float
) -> np.ndarray:
    """Sample truncated NFW radii by rejection on the enclosed-mass profile.

    Parameters
    ----------
    rng : np.random.Generator
        Source of randomness.
    n : int
        Sample count.
    scale : float
        Scale radius ``r_s``.
    truncation : float
        Truncation radius in units of ``r_s``.

    Returns
    -------
    np.ndarray
        ``(n,)`` radii in ``(0, truncation * scale]``. Uses the exact NFW
        enclosed mass ``m(x) = ln(1 + x) - x / (1 + x)`` normalised to the
        truncation radius, inverted numerically on a fine grid.
    """
    x_grid = np.linspace(1.0e-4, truncation, 4096)
    m_grid = np.log1p(x_grid) - x_grid / (1.0 + x_grid)
    m_grid /= m_grid[-1]
    u = rng.uniform(0.0, 1.0, size=n)
    return scale * np.interp(u, m_grid, x_grid)


def _isotropic_directions(rng: np.random.Generator, n: int) -> np.ndarray:
    """Return ``n`` unit vectors uniform on the sphere.

    Parameters
    ----------
    rng : np.random.Generator
        Source of randomness.
    n : int
        Vector count.

    Returns
    -------
    np.ndarray
        ``(n, 3)`` unit vectors.
    """
    cos_t = rng.uniform(-1.0, 1.0, size=n)
    sin_t = np.sqrt(np.maximum(1.0 - cos_t**2, 0.0))
    phi = rng.uniform(0.0, 2.0 * np.pi, size=n)
    return np.stack([sin_t * np.cos(phi), sin_t * np.sin(phi), cos_t], axis=1)


def sample_composite(config: TruthConfig) -> np.ndarray:
    """Realise the composite as equal-mass particle positions.

    Parameters
    ----------
    config : TruthConfig
        Generating configuration.

    Returns
    -------
    np.ndarray
        ``(num_particles, 3)`` positions in float64. Component membership is by
        contiguous blocks -- bulge, disc, halo, then perturber -- so a caller
        can recover component labels from the counts if it needs them.
    """
    rng = np.random.default_rng(config.seed)
    n = int(config.num_particles)
    n_pert = (
        int(round(n * config.perturber_fraction)) if config.perturber != "none" else 0
    )
    n_body = n - n_pert
    n_bulge = int(round(n_body * config.bulge_fraction))
    n_disc = int(round(n_body * config.disc_fraction))
    n_halo = n_body - n_bulge - n_disc

    bulge = _hernquist_radii(rng, n_bulge, config.bulge_scale)[:, None] * (
        _isotropic_directions(rng, n_bulge)
    )

    disc_r = rng.exponential(config.disc_scale_length, size=n_disc)
    disc_phi = rng.uniform(0.0, 2.0 * np.pi, size=n_disc)
    disc_z = rng.laplace(0.0, config.disc_scale_height, size=n_disc)
    disc = np.stack(
        [disc_r * np.cos(disc_phi), disc_r * np.sin(disc_phi), disc_z], axis=1
    )

    halo = _nfw_radii(rng, n_halo, config.halo_scale, config.halo_truncation)[
        :, None
    ] * _isotropic_directions(rng, n_halo)

    parts = [bulge, disc, halo]
    if n_pert > 0:
        # Plummer-like: r = a / sqrt(u^(-2/3) - 1).
        u = rng.uniform(0.02, 1.0, size=n_pert)
        r_pert = config.perturber_scale / np.sqrt(u ** (-2.0 / 3.0) - 1.0)
        pert = r_pert[:, None] * _isotropic_directions(rng, n_pert) + np.asarray(
            config.perturber_offset, dtype=np.float64
        )
        parts.append(pert)
    positions = np.concatenate(parts, axis=0).astype(np.float64)
    assert positions.shape == (n, 3)
    return positions


def sample_tracers(
    config: TruthConfig, source_positions: np.ndarray, *, seed_offset: int = 1
) -> np.ndarray:
    """Sample the tracer positions at which accelerations are observed.

    Parameters
    ----------
    config : TruthConfig
        Generating configuration; ``tracer_mode`` selects the scheme.
    source_positions : np.ndarray
        ``(N, 3)`` source positions, used by ``"from_particles"``.
    seed_offset : int
        Added to ``config.seed`` so tracers never reuse the source stream.

    Returns
    -------
    np.ndarray
        ``(num_tracers, 3)`` positions in float64.

    Raises
    ------
    ValueError
        If ``config.tracer_mode`` is not a recognised mode.
    """
    rng = np.random.default_rng(int(config.seed) + int(seed_offset))
    m = int(config.num_tracers)
    if config.tracer_mode == "independent":
        radii = config.tracer_radius * np.cbrt(rng.uniform(0.0, 1.0, size=m))
        return (radii[:, None] * _isotropic_directions(rng, m)).astype(np.float64)
    if config.tracer_mode == "from_particles":
        picks = rng.integers(0, source_positions.shape[0], size=m)
        # Offset by a fraction of the softening so no tracer sits exactly on a
        # source; the forward operator would still be finite, but the field
        # there is dominated by one particle and carries little information.
        jitter = 3.0 * config.softening * _isotropic_directions(rng, m)
        return (np.asarray(source_positions)[picks] + jitter).astype(np.float64)
    raise ValueError(
        f"unknown tracer_mode {config.tracer_mode!r}; "
        "expected 'independent' or 'from_particles'"
    )


@dataclass(frozen=True)
class GroundTruth:
    """One realisation: sources, tracers, and the observed field.

    Attributes
    ----------
    config : TruthConfig
        The configuration that produced it, for the results JSON.
    source_positions : np.ndarray
        ``(N, 3)`` true source positions.
    source_mass : float
        The single mass every source carries, ``total_mass / N``.
    tracer_positions : np.ndarray
        ``(M, 3)`` observation points.
    observed_accelerations : Optional[np.ndarray]
        ``(M, 3)`` accelerations at the tracers, with noise applied, or
        ``None`` until :func:`make_ground_truth` has generated them.
    clean_accelerations : Optional[np.ndarray]
        The same before noise, so the noise realisation is recoverable.
    """

    config: TruthConfig
    source_positions: np.ndarray
    source_mass: float
    tracer_positions: np.ndarray
    observed_accelerations: Optional[np.ndarray] = None
    clean_accelerations: Optional[np.ndarray] = None

    @property
    def masses(self: "GroundTruth") -> np.ndarray:
        """Return the equal source masses as an array.

        Returns
        -------
        np.ndarray
            ``(N,)`` filled with ``source_mass``. Built on demand because the
            whole point is that this is not free data -- there is one number.
        """
        return np.full(
            (self.source_positions.shape[0],), self.source_mass, dtype=np.float64
        )

    def record(self: "GroundTruth") -> Dict[str, Any]:
        """Return the JSON-safe generating record for a results file.

        Returns
        -------
        Dict[str, Any]
            The config plus the derived ``source_mass`` and counts.
        """
        out = self.config.as_record()
        out["source_mass"] = float(self.source_mass)
        out["N"] = int(self.source_positions.shape[0])
        out["M"] = int(self.tracer_positions.shape[0])
        return out


def make_ground_truth(
    config: TruthConfig,
    *,
    generate_observations: bool = True,
) -> GroundTruth:
    """Realise a seeded ground truth and, by default, its observed field.

    Parameters
    ----------
    config : TruthConfig
        Generating configuration.
    generate_observations : bool
        When ``True`` (default) the observed accelerations are produced with
        jaccpot at ``config.generating_order`` / ``config.generating_theta``
        via :func:`~jaccpot.applications.density_reconstruction.forward.make_forward_operator`,
        then noised. When ``False`` only positions are realised -- useful for
        tests that supply their own operator.

    Returns
    -------
    GroundTruth
        The realisation.
    """
    positions = sample_composite(config)
    source_mass = float(config.total_mass) / float(config.num_particles)
    tracers = sample_tracers(config, positions)
    truth = GroundTruth(
        config=config,
        source_positions=positions,
        source_mass=source_mass,
        tracer_positions=tracers,
    )
    if not generate_observations:
        return truth

    # Local import: forward.py imports nothing from here at module level either
    # way, but keeping truth.py importable without jax keeps the sampling
    # testable on its own.
    from jaccpot.applications.density_reconstruction.forward import (
        make_forward_operator,
    )

    operator = make_forward_operator(
        tracer_positions=tracers,
        source_mass=source_mass,
        num_sources=positions.shape[0],
        softening=config.softening,
        order=config.generating_order,
        theta=config.generating_theta,
        leaf_size=config.generating_leaf_size,
    )
    clean = np.asarray(operator.evaluate(positions), dtype=np.float64)
    rng = np.random.default_rng(int(config.seed) + 2)
    if config.noise_fraction > 0.0:
        scale = config.noise_fraction * np.linalg.norm(clean, axis=1, keepdims=True)
        observed = clean + rng.normal(0.0, 1.0, size=clean.shape) * scale
    else:
        observed = clean.copy()
    return GroundTruth(
        config=config,
        source_positions=positions,
        source_mass=source_mass,
        tracer_positions=tracers,
        observed_accelerations=observed,
        clean_accelerations=clean,
    )
