"""Section 7 tests 1-5: the operator, its invariants, the gate, switch detection.

Written first, per the prompt. Everything here is tiny-N CPU work; the GPU runs
depend on these holding.
"""

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from jaccpot.applications.density_reconstruction import (
    SwitchLog,
    assert_masses_frozen_and_equal,
    fingerprint_prepared_state,
    make_forward_operator,
    make_ground_truth,
)
from jaccpot.applications.density_reconstruction.loss import total_loss
from jaccpot.applications.density_reconstruction.parameterize import (
    positions_params,
    to_positions,
)
from jaccpot.applications.density_reconstruction.truth import TruthConfig
from jaccpot.autodiff import direct_sum_gravitational_acceleration

SOFTENING = 1.0e-2


def _small_truth(n=192, m=48, seed=0, **overrides):
    """A tiny composite truth with observations generated by jaccpot."""
    cfg = TruthConfig(
        num_particles=n,
        num_tracers=m,
        seed=seed,
        softening=SOFTENING,
        generating_order=8,
        generating_theta=0.3,
        generating_leaf_size=16,
        **overrides,
    )
    return make_ground_truth(cfg)


def _operator(truth, *, order=8, theta=0.3, leaf_size=16, **kw):
    return make_forward_operator(
        tracer_positions=truth.tracer_positions,
        source_mass=truth.source_mass,
        num_sources=truth.source_positions.shape[0],
        softening=truth.config.softening,
        order=order,
        theta=theta,
        leaf_size=leaf_size,
        **kw,
    )


# 1 -----------------------------------------------------------------------------
def test_forward_matches_direct_sum():
    """The operator is the field of the sources at the tracers, nothing else.

    A wrong operator would produce a beautiful but meaningless reconstruction,
    so this is checked against the exact O(N^2) sum over the sources only,
    sliced to the tracer rows. Zero-mass tracers must contribute nothing.
    """
    truth = _small_truth()
    op = _operator(truth)
    acc = np.asarray(op.evaluate(truth.source_positions))

    combined = jnp.concatenate(
        [jnp.asarray(truth.source_positions), jnp.asarray(truth.tracer_positions)]
    )
    masses = jnp.concatenate(
        [jnp.asarray(truth.masses), jnp.zeros((truth.tracer_positions.shape[0],))]
    )
    ref_all = direct_sum_gravitational_acceleration(
        combined, masses, softening=SOFTENING
    )
    ref = np.asarray(ref_all)[truth.source_positions.shape[0] :]

    rel = np.linalg.norm(acc - ref) / np.linalg.norm(ref)
    assert acc.shape == ref.shape == (truth.tracer_positions.shape[0], 3)
    assert rel < 1e-5, f"operator vs direct sum rel L2 {rel:.3e}"


# 2 -----------------------------------------------------------------------------
def test_masses_frozen_and_equal():
    """Masses are inputs, equal, and absent from the differentiated pytree."""
    truth = _small_truth()
    params = positions_params(truth.source_positions)

    # The real pytree passes.
    assert_masses_frozen_and_equal(params, truth.masses)

    # Every mass equals every other.
    assert np.all(truth.masses == truth.masses[0])
    assert truth.masses[0] == pytest.approx(
        truth.config.total_mass / truth.config.num_particles
    )

    # A mass leaf, under any of its names, is refused ...
    for name in ("masses", "mass", "m"):
        with pytest.raises(ValueError, match="mass leaf"):
            assert_masses_frozen_and_equal(
                {**params, name: jnp.asarray(truth.masses)}, truth.masses
            )
    # ... and so is the mass array smuggled in under another name.
    with pytest.raises(ValueError, match="smuggled"):
        assert_masses_frozen_and_equal(
            {**params, "weights": jnp.asarray(truth.masses)}, truth.masses
        )
    # ... and unequal masses.
    unequal = truth.masses.copy()
    unequal[0] *= 1.001
    with pytest.raises(ValueError, match="equal"):
        assert_masses_frozen_and_equal(params, unequal)

    # The gradient has exactly one leaf and it is positions.
    op = _operator(truth)
    state = op.prepare(truth.source_positions)
    grads = jax.grad(
        lambda p: jnp.sum(op.evaluate_at_topology(state, to_positions(p)) ** 2)
    )(params)
    assert set(grads) == {"positions"}
    assert grads["positions"].shape == truth.source_positions.shape


# 3 -----------------------------------------------------------------------------
def test_gradient_matches_finite_difference_within_topology_epoch():
    """The correctness gate: FD vs jax.grad through the full loss, pinned topology.

    Both arms call the same frozen-topology function. Pinning is essential -- an
    FD step that crossed a switch boundary would legitimately disagree, and a
    test that ignored this would fail for the wrong reason. Directional FD keeps
    it cheap: two evaluations per direction, not per coordinate.
    """
    truth = _small_truth()
    op = _operator(truth)
    observed = jnp.asarray(truth.observed_accelerations)
    start = np.asarray(truth.source_positions) + 0.02 * np.random.default_rng(
        3
    ).standard_normal(truth.source_positions.shape)
    state = op.prepare(start)

    def loss(pos):
        pred = op.evaluate_at_topology(state, pos)
        return total_loss(pred, observed, weights={"data": 1.0}, scale=1.0)[0]

    x = jnp.asarray(start)
    grad = jax.grad(loss)(x)
    assert bool(jnp.all(jnp.isfinite(grad)))

    rng = np.random.default_rng(11)
    worst = 0.0
    for _ in range(4):
        direction = rng.standard_normal(x.shape)
        direction = jnp.asarray(direction / np.linalg.norm(direction))
        eps = 1e-6
        fd = float((loss(x + eps * direction) - loss(x - eps * direction)) / (2 * eps))
        ad = float(jnp.sum(grad * direction))
        rel = abs(fd - ad) / (abs(fd) + 1e-300)
        worst = max(worst, rel)
    assert worst < 1e-4, f"worst directional FD-vs-AD rel error {worst:.3e}"


# 4 -----------------------------------------------------------------------------
def test_mac_stop_gradient_enforced():
    """Asking for a differentiated MAC raises; so does a mass-dependent MAC."""
    truth = _small_truth(n=64, m=16)
    with pytest.raises(ValueError, match="fixed-topology contract"):
        _operator(truth, differentiate_mac=True)
    for mac in ("dehnen_error", "dehnen_theta"):
        with pytest.raises(ValueError, match="mass-dependent"):
            _operator(truth, mac_type=mac)
    # A geometric MAC is fine.
    _operator(truth, mac_type="dehnen")


# 5 -----------------------------------------------------------------------------
def test_topology_switch_detection():
    """A structure-changing perturbation is logged; a quantisation-only one is not.

    Thresholds come from measurement on this preset: 1e-9 changes nothing; 1e-6
    changes only the Morton codes; 1e-1 changes the permutation and the near
    CSR. The middle case is the design decision -- codes are excluded from
    identity, so it must NOT register as a switch even though `leaf_codes`
    differs.
    """
    truth = _small_truth()
    op = _operator(truth)
    base = np.asarray(truth.source_positions)
    rng = np.random.default_rng(5)
    noise = rng.standard_normal(base.shape)

    s0 = op.prepare(base)
    s_same = op.prepare(base)
    s_tiny = op.prepare(base + 1e-9 * noise)
    s_codes = op.prepare(base + 1e-6 * noise)
    s_big = op.prepare(base + 1e-1 * noise)

    # Determinism: identical input, identical fingerprint.
    assert fingerprint_prepared_state(s0) == fingerprint_prepared_state(s_same)

    log = SwitchLog()
    assert log.observe(s0, iteration=0) == ()
    assert log.observe(s_same, iteration=1) == ()
    assert log.observe(s_tiny, iteration=2) == ()

    # Morton codes may move at 1e-6 while the structure does not (measured on
    # this preset). Whether or not they moved for this seed, it is not a switch.
    assert log.observe(s_codes, iteration=3) == ()

    changed = log.observe(s_big, iteration=4)
    assert changed, "a 0.1 perturbation must change the structure"
    assert "permutation" in changed or "near_pairs" in changed

    summary = log.summary()
    assert summary["switches"] == 1
    assert summary["comparisons"] == 4
    assert summary["switch_rate"] == pytest.approx(0.25)
    assert summary["interaction_switches"] <= summary["switches"]
    assert summary["switch_metric"] == "radix_topology_excluding_morton_codes"
    assert summary["events"][0]["iteration"] == 4
