"""Section 7 tests 6-8: the fits themselves, and the softening they must respect.

The parametric case has to recover truth before the high-dimensional runs are
worth attempting -- if the small case does not work, the big one will not
either. That ordering is why these live in their own module and run after the
operator tests.

All three are marked ``slow``: they cost 38 s, 41 s and 28 s on the CPU
backend, which is a gradient-descent fit and not a unit test's worth of time.
The CI smoke subset (``-m "not slow and not experimental"``) therefore skips
them, and the full tier runs them.

All three fits pin the topology for their epoch (``rebuild_cadence`` equal to
the iteration count) **except test 7**, which is specifically about the rebuilt
path. Pinning where the rebuild is not the subject buys ``jit_within_epoch``,
which turns a 150-second CPU fit into a 15-second one; the switching machinery
has its own tests in ``test_density_reconstruction_core.py``.
"""

import numpy as np
import pytest

from jaccpot.applications.density_reconstruction import (
    make_forward_operator,
    make_ground_truth,
)
from jaccpot.applications.density_reconstruction.diagnostics import field_residual
from jaccpot.applications.density_reconstruction.fit import FitConfig, run_fit
from jaccpot.applications.density_reconstruction.loss import Regularization
from jaccpot.applications.density_reconstruction.parameterize import (
    initial_positions,
    make_parameterization,
)
from jaccpot.applications.density_reconstruction.truth import TruthConfig

SOFTENING = 1.0e-2


def _truth(n, m, *, seed=0, **overrides):
    """A tiny seeded truth with observations generated by jaccpot."""
    config = TruthConfig(
        num_particles=n,
        num_tracers=m,
        seed=seed,
        softening=SOFTENING,
        generating_order=6,
        generating_theta=0.4,
        generating_leaf_size=16,
        **overrides,
    )
    return config, make_ground_truth(config)


def _operator(config, truth):
    """The observation operator matching a truth configuration."""
    return make_forward_operator(
        tracer_positions=truth.tracer_positions,
        source_mass=truth.source_mass,
        num_sources=int(config.num_particles),
        softening=config.softening,
        order=6,
        theta=0.4,
        leaf_size=16,
    )


def _min_pair_distance(positions):
    """Exact all-pairs minimum separation. Only for the tiny N used here."""
    x = np.asarray(positions, dtype=np.float64)
    delta = x[:, None, :] - x[None, :, :]
    d = np.sqrt(np.sum(delta**2, axis=-1))
    np.fill_diagonal(d, np.inf)
    return float(d.min())


# 6 -----------------------------------------------------------------------------
@pytest.mark.slow
def test_recovers_parametric_truth_noiseless():
    """The gate on everything downstream: the 7-parameter fit finds truth.

    Noiseless, no regularisation, every parameter started 0.1 away from its true
    value -- which for the three log scales is a 10.5% error in the scale itself,
    and for the tilts and the flattening an absolute offset. If this does not
    converge, no high-dimensional run is interpretable.
    """
    config, truth = _truth(160, 80)
    operator = _operator(config, truth)
    parameterization = make_parameterization("parametric", config=config)
    true_values = {k: float(v) for k, v in parameterization.true_params(config).items()}
    start = {name: value + 0.1 for name, value in true_values.items()}

    iterations = 400
    result = run_fit(
        operator=operator,
        observed=truth.observed_accelerations,
        parameterization=parameterization,
        initial_params=parameterization.pack(start),
        config=FitConfig(
            num_iterations=iterations,
            learning_rate=0.02,
            rebuild_cadence=iterations,
            jit_within_epoch=True,
            regularization=Regularization.none(),
            history_every=iterations,
        ),
    )

    assert parameterization.num_free == 7, "no perturber, so 7 free parameters"
    assert result.final_loss < result.initial_loss

    errors = {
        name: abs(float(result.params[name]) - true_values[name])
        for name in parameterization.names
    }
    worst = max(errors.values())
    assert worst < 1.0e-2, f"parametric fit did not recover truth: {errors}"
    # And the loss really did collapse, not merely improve.
    assert (
        result.final_loss < 1.0e-6 * result.initial_loss
    ), f"loss {result.initial_loss:.3e} -> {result.final_loss:.3e}"


# 7 -----------------------------------------------------------------------------
@pytest.mark.slow
def test_field_residual_decreases_positions():
    """The high-dimensional fit reduces the field residual, through rebuilds.

    ``rebuild_cadence = 1`` deliberately: this is the one test whose subject is
    the per-iteration-rebuild path, so it must not pin the topology. The
    assertion is on the **field residual**, the section's primary metric, and
    not on density agreement or position error -- which the section explicitly
    does not claim to recover.
    """
    config, truth = _truth(192, 96)
    operator = _operator(config, truth)
    parameterization = make_parameterization("positions", config=config)
    start = initial_positions(
        truth.source_positions, mode="perturbed_truth", seed=3, perturbation=0.05
    )

    before = field_residual(operator.evaluate(start), truth.observed_accelerations)

    result = run_fit(
        operator=operator,
        observed=truth.observed_accelerations,
        parameterization=parameterization,
        initial_params=parameterization.pack(start),
        config=FitConfig(
            num_iterations=8,
            learning_rate=2.0e-3,
            rebuild_cadence=1,
            regularization=Regularization.none(),
            history_every=1,
        ),
    )

    after = field_residual(
        operator.evaluate(result.positions), truth.observed_accelerations
    )

    assert parameterization.num_free == 3 * 192
    assert (
        after["rel_l2"] < before["rel_l2"]
    ), f"field residual did not fall: {before['rel_l2']:.4e} -> {after['rel_l2']:.4e}"
    assert result.final_loss < result.initial_loss
    # Every iteration rebuilt, so the switch log saw one state per iteration.
    assert result.switch_summary is not None
    assert result.switch_summary["extensive"]["observations"] == 8
    # The intensive rates exist and are rates, not counts.
    mean = result.switch_summary["intensive"]["mean"]
    assert 0.0 <= mean["slot_churn"] <= 1.0
    assert 0.0 <= mean["near_pair_churn"] <= 1.0
    # Every history row records whether it rebuilt, so a figure can mark them.
    assert all(row["rebuilt"] for row in result.history)


# 8 -----------------------------------------------------------------------------
@pytest.mark.slow
def test_softening_respected():
    """The optimiser must not be allowed to exploit the P2P singularity.

    Position gradients of the near-field term scale like ``1 / r^3``, so a pair
    driven inside the softening length produces an enormous gradient and a
    meaningless field. This starts a pair at a twentieth of the softening length
    -- close enough that an unregularised fit has every incentive to keep it
    there -- and checks the regularised fit pushes it back out.

    The comparison against an unregularised run on the *same* start is the
    point: it is what makes this a statement about the regulariser rather than
    about the data term happening to be benign.
    """
    config, truth = _truth(128, 64)
    operator = _operator(config, truth)
    parameterization = make_parameterization("positions", config=config)

    start = np.array(truth.source_positions, dtype=np.float64)
    # Put the pair in the same leaf by construction: coincident-then-separated
    # particles land together in any partition built from these positions.
    start[1] = start[0] + np.array([SOFTENING / 20.0, 0.0, 0.0])
    assert _min_pair_distance(start) < 0.1 * SOFTENING

    def fit(regularization, iterations=60):
        return run_fit(
            operator=operator,
            observed=truth.observed_accelerations,
            parameterization=parameterization,
            initial_params=parameterization.pack(start),
            config=FitConfig(
                num_iterations=iterations,
                learning_rate=1.0e-3,
                rebuild_cadence=iterations,
                jit_within_epoch=True,
                regularization=regularization,
                history_every=iterations,
            ),
        )

    regularized = fit(Regularization(softening_floor=1.0e3, spacing_smoothness=0.0))
    unregularized = fit(Regularization.none())

    separation_regularized = _min_pair_distance(regularized.positions)
    separation_unregularized = _min_pair_distance(unregularized.positions)

    # The regulariser opened the pair up by at least an order of magnitude on
    # the run that was paying for it ...
    assert separation_regularized > 10.0 * (SOFTENING / 20.0), (
        f"regularised fit left the pair at {separation_regularized:.3e}, "
        f"floor is {SOFTENING:.3e}"
    )
    # ... to a stated fraction of the softening length ...
    assert separation_regularized > 0.5 * SOFTENING
    # ... and did so *because* of the regulariser, not despite it.
    assert separation_regularized > 5.0 * separation_unregularized, (
        f"regularised {separation_regularized:.3e} vs unregularised "
        f"{separation_unregularized:.3e}: the term is not doing the work"
    )

    # The penalty itself fell, and is reported even by the run that paid nothing.
    assert (
        regularized.history[-1]["components"]["softening_floor"]
        < unregularized.history[-1]["components"]["softening_floor"]
    )
    assert (
        "softening_floor" in unregularized.history[-1]["components"]
    ), "an unregularised run must still report what it was not paying"
